name: Build Kivy APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Setup Android SDK & Accept Licenses
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/repositories.cfg

        yes | sdkmanager --licenses || true
        yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true

    - name: Initialize Buildozer spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-kivy-apk
        path: bin/*.apk
