name: Build Kivy APK

on:
  push:
    paths:
      - 'mainmob.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libffi-dev build-essential git zip unzip openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Rename mainmob.py to main.py
        run: mv mainmob.py main.py

      - name: Generate buildozer.spec
        run: buildozer init

      - name: Fix buildozer.spec for Kivy app
        run: |
          sed -i 's/title = .*/title = ToDoApp/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/^# *android\\.logcat_filters = .*/android.logcat_filters = *:S python:D/' buildozer.spec
          sed -i 's/^# *requirements = .*/requirements = python3,kivy/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: todo-app
          path: bin/*.apk
