name: Build Kivy APK

on:
  push:
    paths:
      - 'mainmob.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies (Java, SDK, AIDL)
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libffi-dev libssl-dev \
              libsqlite3-dev zlib1g-dev libjpeg-dev libandroid-tools adb unzip zip \
              openjdk-17-jdk wget python3-pip

          echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "export PATH=\$JAVA_HOME/bin:\$PATH" >> $GITHUB_ENV

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Rename mainmob.py to main.py
        run: mv mainmob.py main.py

      - name: Create buildozer.spec
        run: buildozer init

      - name: Modify buildozer.spec
        run: |
          sed -i 's/title = .*/title = ToDoApp/' buildozer.spec
          sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/^# *android\\.logcat_filters = .*/android.logcat_filters = *:S python:D/' buildozer.spec
          sed -i 's/^# *requirements = .*/requirements = python3,kivy/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: todo-app
          path: bin/*.apk
