name: Build Kivy APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip
        pip install cython buildozer

    - name: Create buildozer.spec and main.py
      run: |
        cp mainmob.py main.py
        buildozer init

    - name: Configure buildozer.spec
      run: |
        sed -i 's/^title = .*/title = TypeKaroApp/' buildozer.spec
        sed -i 's/^package.name = .*/package.name = typekaro/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.type.karo/' buildozer.spec
        sed -i 's/^source.include_exts = .*/source.include_exts = py,kv,png,jpg,ttf/' buildozer.spec
        sed -i 's/^# android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
        sed -i 's/^# android.api = 33/android.api = 33/' buildozer.spec
        sed -i 's/^# android.ndk = 25b/android.ndk = 25b/' buildozer.spec
        sed -i 's/^# android.build_tools = 34.0.0/android.build_tools = 34.0.0/' buildozer.spec
        sed -i 's/^# android.sdk = 24/android.sdk = 24/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: typekaro-apk
        path: bin/*.apk
